number:
  output: <NUM,{VALUE}>
id:
  output: <ID,{VALUE}>
string:
  output: <LITERAL,{VALUE}>
bool: 
  output: <BOOL,{VALUE}>
float:
  output: <FLOAT,{VALUE}>
char: 
  output: <CHAR,{VALUE}>
error: 
  output: <ERROR,{VALUE}>