Program2:
  -
    - IdList
    - Program
  -
    - FunctionDecl
FunctionDecl:
  -
    - "("
    - FormalList
    - ")"
    - "{"
    - VarDecl
    - StmtList
    - "}"
    - FunctionDecl1
FunctionDecl1:
  -
    - Program
  -
    - Lambda
Program1:
  -
    - ID
    - Program2
Program:
  -
    - Type
    - Program1
VarDecl:
  -
    - Type
    - IdList
    - ;
    - VarDecl
  -
    - LAMBDA
IdList:
  -
    - ID
    - Array1
Array2:
  -
    - ","
    - ID
    - Array1
  -
    - LAMBDA
Array1:
  -
    - Array
    - Array2
Array:
  -
    - "["
    - NUM
    - "]"
  -
    - LAMBDA
FormalRest:
  -
    - ","
    - Type
    - ID
    - Array
    - FormalRest
  -
    - LAMBDA
FormalList:
  -
    - Type
    - ID
    - Array
    - FormalRest
  -
    - LAMBDA
Type:
  -
    - int
  -
    - float
  -
    - bool
  -
    - ID
  -
    - char
StmtList1:
  -
    - Stmt
    - StmtLis1
  -
    - LAMBDA
StmtList:
  -
    - Stmt
    - StmtList1
Stmt:
  -
    - if
    - (
    - Expr
    - )
    - Stmt
    - else
    - Stmt
  -
    - while
    - (
    - Expr
    - )
    - Stmt
  -
    - break
    - ;
  -
    - print
    - (
    - ExprList
    - )
    - ;
  -
    - readln
    - (
    - Expr
    - )
    - ;
  -
    - return
    - Expr
    - ;
  -
    - "{"
    - StmtList
    - "}"
  -
    - Expr
    - ;
ExprListTail1:
  -
    - ","
    - ExprListTail
  -
    - LAMBDA
ExprListTail:
  -
    - Expr
    - ExprListTail1
ExprList:
  -
    - ExprListTail
  -
    - LAMBDA
Ident:
  -
    - "("
    - ExprList
    - ")"
  -
    - LAMBDA
Primary:
  -
    - "("
    - Expr
    - ")"
  -
    - ID
    - Ident
  -
    - NUM
  -
    - LITERAL
  -
    - ASCII
  -
    - true
  -
    - false
CmplExpr:
  -
    - "="
    - Expr
  -
    - OrExpr
    - Expr
AltExpr:
  -
    - "["
    - Expr
    - "]"
  -
    - CmplExpr
  -
    - LAMBDA
Expr:
  -
    - Primary
    - AltExpr
  -
    - UnaryOp
    - ExtraExpr
ExtraExpr:
  -
    - Expr
  -
    - CmplExpr
UnaryOp:
  -
    - ++
  -
    - â€“
  -
    - LAMBDA
OrExpr:
  -
    - AndExpr
    - OrExpr1
OrExpr1:
  -
    - "||"
    - AndExpr
    - OrExpr1
  -
    - LAMBDA
AndExpr:
  -
    - CompExpr
    - AndExpr1
AndExpr1:
  -
    - "&&"
    - CompExpr
    - AndExpr1
  -
    - LAMBDA
CompExpr:
  -
    - AddExpr
    - CompExpr1
CompExpr1:
  -
    - CompOp
    - AddExpr
    - CompExpr1
  -
    - LAMBDA
CompOp:
  -
    - "<"
  -
    - ">"
  -
    - "<="
  -
    - ">="
  -
    - "=="
  -
    - "!="
AddExpr:
  -
    - MulExpr
    - AddExpr1
AddExpr1:
  -
    - AddOp
    - MulExpr
    - AddExpr1
  -
    - LAMBDA
AddOp:
  -
    - "+"
  -
    - "-"
MulExpr:
  -
    - UnaryExpr
    - MulExpr1
MulExpr1:
  -
    - MulOp
    - UnaryExpr
    - MulExpr1
  -
    - LAMBDA
MulOp:
  -
    - "*"
  -
    - "/"
  -
    - "%"
UnaryExpr:
  -
    - UnaryOp
    - UnaryExpr
  -
    - Primary